---
name: 'Build Containers'

on:
  workflow_dispatch:
    inputs:
      version:
        description: Image tag to publish
        required: true
        default: klarc-playlists-v1

jobs:
  build-containers-common:
    runs-on: ubuntu-latest
    outputs:
      containerver: ${{ steps.getcontainerver.outputs.containerver }}
    steps:
      - name: Get Container Version
        id: getcontainerver
        run: |
          echo "containerver=${{ inputs.version }}" >> "$GITHUB_OUTPUT"

  build-containers:
    needs: build-containers-common
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and Push Image
        env:
          CONTAINERVER: ${{ needs.build-containers-common.outputs.containerver }}
          NEXT_PUBLIC_VERSION: ${{ needs.build-containers-common.outputs.containerver }}
        run: |
          docker buildx build --platform linux/amd64 \
            -f Dockerfile.dev \
            -t ghcr.io/klarc-dev/postiz-app:${{ env.CONTAINERVER }} \
            --build-arg NEXT_PUBLIC_VERSION=${{ env.NEXT_PUBLIC_VERSION }} \
            --pull \
            --no-cache \
            --provenance=false --sbom=false \
            --output "type=registry,name=ghcr.io/klarc-dev/postiz-app:${{ env.CONTAINERVER }}" .

      - name: Verify image
        env:
          CONTAINERVER: ${{ needs.build-containers-common.outputs.containerver }}
        run: docker buildx imagetools inspect ghcr.io/klarc-dev/postiz-app:${{ env.CONTAINERVER }}
